### ISSUE TITLE
It's not working correctly when having a navigation bar on top

### ISSUE THREAD

**Issue by alanfeng99** [appfigures/AFSwipeToHide#3] opened 2015-04-16 02:14 UTC
Hi Sir,

As title, I'm looking into the issue now.
The titleView won't be able to hide fully if the VC has a navigation bar on top.

Any suggestion would be appreciated.

**Comment by oztune** [comment] 2015-04-16 19:47
Do you have some sample code to illustrate the issue?

**Comment by oztune** [comment] 2015-11-30 21:20
I'm closing this issue since I can't reproduce.

**Closed by oztune** 2015-11-30 21:20 UTC
